Create filter credit card method
ResultadosDigitais/rdstation-wp pull request #45
Opened 2020-09-02 20:08 UTC by Seralto

2020-09-03 15:04 UTC, filipenasc commented on includes/resources/rdsm_conversion.php
> +    }
What do you think about looping all the card types to validate them?

This way, when we add a new card type, we'll only need to change the `$cardtypes` array.
```suggestion
foreach($cardtypes as $cardtype) {
    $credit_card_number = preg_match($cardtype, $number);

    if ($credit_card_number) {
      return true;
    }
  }
  
  return false;
```

2020-09-03 15:04 UTC, filipenasc commented on includes/resources/rdsm_conversion.php
> +    $cardtype = array(
```suggestion
    $cardtypes = array(
```

2020-09-03 15:07 UTC, filipenasc reviewed
Do you think that now we can remove these lines safely?

https://github.com/ResultadosDigitais/rdstation-wp/blob/master/includes/resources/rdsm_conversion.php#L22-L36

2020-09-03 17:11 UTC, Seralto commented on includes/resources/rdsm_conversion.php
> +foreach($cardtypes as $cardtype) {
```suggestion
  foreach($cardtypes as $cardtype) {
```

2020-09-03 17:11 UTC, Seralto commented on includes/resources/rdsm_conversion.php
> +  }
```suggestion
    foreach($cardtypes as $cardtype) {
      $credit_card_number = preg_match($cardtype, $number);

      if ($credit_card_number) {
        return true;
      }
    }
```

2020-09-03 17:12 UTC, Seralto commented on includes/resources/rdsm_conversion.php
> +  return false;
```suggestion
    return false;
```

2020-09-03 19:38 UTC, Seralto commented
I don't think so. This filter aims to remove any credit card number that came with a field name that we did not expected.
So, both are necessary.

2020-09-03 20:21 UTC, filipenasc approved these changes

2020-09-04 12:38 UTC, filipenasc requested changes

2020-09-04 12:38 UTC, filipenasc commented on includes/resources/rdsm_conversion.php
> +      $credit_card_number = preg_match($cardtype, $number);
I've received this error when testing on a production blog:

`preg_match() expects parameter 2 to be string, array given`

2020-09-08 12:29 UTC, filipenasc approved these changes

2020-09-08 12:30 UTC, merged

2020-09-29 17:07 UTC, rafaelhancke reviewed
LGTM