feat: add nounce to clear log form
ResultadosDigitais/rdstation-wp pull request #87
Opened 2022-10-11 19:59 UTC by tota1099

Adicionei uma verificação na chamada do CLEAR_LOG para que verifique se a chamada é autentica, ou seja, se foi chamada pela página do RDSM no plugin do wordpress.

### Referencias

[WordPress Nonces](https://codex.wordpress.org/WordPress_Nonces)
[WordPress CSRF Attacks: Vulnerability and Prevention](https://www.malcare.com/blog/wordpress-csrf/)
[Protecting WordPress custom forms from CSRF attack](https://medium.com/geekculture/protecting-wordpress-custom-forms-from-csrf-attack-a5528b91d0df)

2022-10-13 12:21 UTC, AndersonOlvra requested changes

2022-10-13 12:21 UTC, AndersonOlvra commented on integracao-rd-station/includes/events/rdsm_log_file.php
> +    if (!isset($_POST['form_nonce']) || !wp_verify_nonce($_POST['form_nonce'],'log-nonce')) {
Será que faz sentido a gente mudar para `rd-log-nonce` é que o wp ele não diferencia nome de recurso por plugin, já tive alguns problemas com constantes com o mesmo nome de outro plugin quebrar o wordpress e a solução que eles indicam pra isso é justamente o prefixo do plugin. Dei uma olhada no projeto e vi que estamos usando rd- para outros nonces também. 
![image](https://user-images.githubusercontent.com/75985246/195594602-24be074c-8551-4e62-b990-fed42132506f.png)

2022-10-13 12:38 UTC, tota1099 commented on integracao-rd-station/includes/events/rdsm_log_file.php
> +    if (!isset($_POST['form_nonce']) || !wp_verify_nonce($_POST['form_nonce'],'log-nonce')) {
Perfeito Anderson! Vou alterar para seguir esse padrão!

2022-10-13 12:57 UTC, AndersonOlvra approved these changes

2022-10-18 17:37 UTC, tota1099 commented
Já subimos e testamos no wordpress em produção

2022-10-18 17:37 UTC, merged